name: revivegoods
description: "Revive Goods Donation Platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  http: ^1.3.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  # Add your dependencies below this line
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  supabase_flutter: ^2.8.4
  lucide_icons: ^0.257.0
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.0
  geolocator: ^11.0.0
  intl: ^0.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add this assets section for any images you might need later
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

